import React, { useState } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  SafeAreaView,
  Alert,
  ActivityIndicator
} from "react-native";
import { colors } from "../theme/colors";
import { useApp } from "../context/AppContext";

export default function DisputeTerminalScreen({ onNavigate }) {
  const {
    worker,
    contract,
    attendanceLogs,
    verifiedWorkdays,
    expectedEarnings,
    receivedAmount,
    deficitAmount,
    isDeficit
  } = useApp();

  const [generating, setGenerating] = useState(false);
  const [bundleGenerated, setBundleGenerated] = useState(true);
  const [claimSubmitted, setClaimSubmitted] = useState(false);

  const handleGenerateBundle = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      setBundleGenerated(true);
    }, 1200);
  };

  const handleFileClaim = () => {
    setClaimSubmitted(true);
  };

  // Compile formatted evidence text preview
  const evidenceText = `================================================================================
                KARMSETU WAGE THEFT AUDIT & EVIDENCE BUNDLE
         NPU-Driven Wage Protection & Verifiable Work Record System
================================================================================
AUDIT TIMESTAMP    : 2026-08-26 03:00:00 UTC
VERDICT STATUS     : [!] WAGE THEFT ALERT (UNPAID DEFICIT DETECTED)
SEVERITY LEVEL     : CRITICAL FINANCIAL DISCREPANCY
--------------------------------------------------------------------------------
1. WORKER & IDENTITY REFERENCE
--------------------------------------------------------------------------------
Worker Full Name   : ${worker.name}
Worker ID Hash     : ${worker.idHash}
Primary Trade      : ${contract.trade}

--------------------------------------------------------------------------------
2. LOCKED CONTRACT TERMS (TAMPER-PROOF LEDGER)
--------------------------------------------------------------------------------
Contract ID        : #${contract.id}
Locked SHA-256 Hash: ${contract.contractHash}
Agreed Daily Rate  : INR ${contract.dailyRate.toFixed(2)} / day
Contracted Duration: ${contract.durationDays} days
Designated Site    : ${contract.siteLocation}

--------------------------------------------------------------------------------
3. FINANCIAL RECONCILIATION & DEFICIT AUDIT
--------------------------------------------------------------------------------
Verified Workdays  : ${verifiedWorkdays} days (100% Biometric & Geofence Validated)
Total Expected Wage: INR ${expectedEarnings.toLocaleString("en-IN")}.00
Actual Disbursed   : INR ${receivedAmount.toLocaleString("en-IN")}.00
--------------------------------------------------------------------------------
>> UNDERPAYMENT DEFICIT : INR ${deficitAmount.toLocaleString("en-IN")}.00 (${((deficitAmount / (expectedEarnings || 1)) * 100).toFixed(1)}% WITHHELD)
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
4. VERIFIED ATTENDANCE & GEOFENCE AUDIT TRAIL (${attendanceLogs.length} Records)
--------------------------------------------------------------------------------
${attendanceLogs
  .map(
    (log, i) =>
      `  [${(i + 1).toString().padStart(2, "0")}] ${log.date} ${log.time} | GPS: (${log.coords}) | Liveness: PASS | Status: VERIFIED`
  )
  .join("\n")}

================================================================================
LEGAL RECOURSE & EVIDENCE NOTICE:
This document is an automated, tamper-evident evidence bundle generated by
KarmSetu Wage Protection Engine. All timestamps, biometric liveness logs,
and GPS coordinate snapshots are cryptographically tied to the worker's
SHA-256 identity hash and locked contract terms.
================================================================================`;

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.badgeRow}>
            <View
              style={[
                styles.disputeBadge,
                isDeficit ? styles.badgeAlert : styles.badgeNormal
              ]}
            >
              <Text
                style={[
                  styles.disputeBadgeText,
                  isDeficit ? styles.textAlert : styles.textNormal
                ]}
              >
                {isDeficit ? "🚨 DEFICIT DETECTED" : "🛡️ ARBITRATION READY"}
              </Text>
            </View>
            <Text style={styles.stepText}>STEP 5 OF 5</Text>
          </View>
          <Text style={styles.title}>Dispute Terminal</Text>
          <Text style={styles.subtitle}>
            One-tap legal evidence packaging. Convert raw GPS logs and locked wage contracts into an admissible labor evidence bundle.
          </Text>
        </View>

        {/* Deficit Alert Banner */}
        <View
          style={[
            styles.alertBanner,
            isDeficit ? styles.alertBannerActive : styles.alertBannerResolved
          ]}
        >
          <View style={styles.alertHeader}>
            <Text style={styles.alertIcon}>{isDeficit ? "🚨" : "✓"}</Text>
            <View style={styles.alertHeaderText}>
              <Text
                style={[
                  styles.alertTitle,
                  isDeficit ? styles.textAlert : styles.textSuccess
                ]}
              >
                {isDeficit
                  ? "WAGE THEFT ALERT TRIGGERED"
                  : "NO DEFICIT DETECTED"}
              </Text>
              <Text style={styles.alertSub}>
                {isDeficit
                  ? `Shortfall of ₹${deficitAmount.toLocaleString("en-IN")} detected against ${verifiedWorkdays} verified workdays.`
                  : "All logged workdays have been paid in full."}
              </Text>
            </View>
          </View>

          {isDeficit && (
            <View style={styles.deficitPill}>
              <Text style={styles.deficitPillLabel}>UNPAID SHORTFALL:</Text>
              <Text style={styles.deficitPillValue}>
                ₹{deficitAmount.toLocaleString("en-IN")}
              </Text>
            </View>
          )}
        </View>

        {/* Prominent One-Tap Evidence Bundle Generator Button */}
        <View style={styles.generatorCard}>
          <Text style={styles.generatorTitle}>
            ⚡ ONE-TAP EVIDENCE BUNDLE GENERATOR
          </Text>
          <Text style={styles.generatorDesc}>
            Packages cryptographic SHA-256 contract terms, timestamped biometric liveness entries, and GPS coordinates into an exportable proof bundle.
          </Text>

          <TouchableOpacity
            style={[
              styles.generateButton,
              isDeficit ? styles.btnAlert : styles.btnNormal
            ]}
            onPress={handleGenerateBundle}
            disabled={generating}
            activeOpacity={0.85}
          >
            {generating ? (
              <ActivityIndicator color="#FFFFFF" />
            ) : (
              <Text style={styles.generateButtonText}>
                📁 Generate One-Tap Evidence Bundle (.txt)
              </Text>
            )}
          </TouchableOpacity>
        </View>

        {/* Live Evidence Bundle Text Viewer Card */}
        {bundleGenerated && (
          <View style={styles.bundleViewerCard}>
            <View style={styles.bundleViewerHeader}>
              <Text style={styles.viewerTitle}>📄 COMPILED EVIDENCE BUNDLE</Text>
              <View style={styles.tamperProofBadge}>
                <Text style={styles.tamperProofText}>CRYPTOGRAPHICALLY SIGNED</Text>
              </View>
            </View>

            {/* Terminal Preformatted Text Area */}
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              style={styles.textScroll}
            >
              <Text style={styles.terminalText}>{evidenceText}</Text>
            </ScrollView>

            {/* Secondary Action Row */}
            <View style={styles.bundleActionRow}>
              <TouchableOpacity
                style={styles.actionPill}
                onPress={() => Alert.alert("Export", "Evidence bundle copied to clipboard!")}
              >
                <Text style={styles.actionPillText}>📋 Copy Text</Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={styles.actionPillPrimary}
                onPress={handleFileClaim}
              >
                <Text style={styles.actionPillPrimaryText}>
                  {claimSubmitted ? "✓ Claim Dispatched" : "⚖️ Dispatch to Labor Board"}
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* Claim Dispatch Notice */}
        {claimSubmitted && (
          <View style={styles.submittedCard}>
            <Text style={styles.submittedTitle}>✓ DISPUTE CLAIM DISPATCHED</Text>
            <Text style={styles.submittedBody}>
              Evidence package reference #KS-ARB-{Date.now().toString().slice(-6)} sent to Trade Union & Labor Conciliation Officer.
            </Text>
          </View>
        )}

        {/* Loop Back Navigation Button */}
        <TouchableOpacity
          style={styles.loopButton}
          onPress={() => onNavigate && onNavigate("Onboarding")}
        >
          <Text style={styles.loopButtonText}>↺ Return to Onboarding (Loop Tour)</Text>
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background
  },
  container: {
    padding: 20,
    paddingBottom: 40
  },
  header: {
    marginBottom: 18
  },
  badgeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8
  },
  disputeBadge: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6
  },
  badgeAlert: {
    backgroundColor: colors.dangerGlow,
    borderColor: colors.danger
  },
  badgeNormal: {
    backgroundColor: colors.primaryGlow,
    borderColor: colors.primary
  },
  disputeBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 1
  },
  textAlert: {
    color: colors.danger
  },
  textNormal: {
    color: colors.primary
  },
  textSuccess: {
    color: colors.success
  },
  stepText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "600"
  },
  title: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: 0.5
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: 6,
    lineHeight: 20
  },
  alertBanner: {
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 16,
    marginBottom: 16
  },
  alertBannerActive: {
    backgroundColor: "#1A060B",
    borderColor: colors.danger
  },
  alertBannerResolved: {
    backgroundColor: "#051A0F",
    borderColor: colors.success
  },
  alertHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12
  },
  alertIcon: {
    fontSize: 24
  },
  alertHeaderText: {
    flex: 1
  },
  alertTitle: {
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.5
  },
  alertSub: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
    lineHeight: 18
  },
  deficitPill: {
    marginTop: 12,
    backgroundColor: "#000000",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#4A121A"
  },
  deficitPillLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700"
  },
  deficitPillValue: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: "900"
  },
  generatorCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 18,
    marginBottom: 16
  },
  generatorTitle: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 6
  },
  generatorDesc: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14
  },
  generateButton: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center"
  },
  btnAlert: {
    backgroundColor: colors.danger,
    shadowColor: colors.danger,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10
  },
  btnNormal: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8
  },
  generateButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.5
  },
  bundleViewerCard: {
    backgroundColor: "#05070A",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 16,
    marginBottom: 16
  },
  bundleViewerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12
  },
  viewerTitle: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8
  },
  tamperProofBadge: {
    backgroundColor: "#00F0FF1A",
    borderColor: colors.primary,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4
  },
  tamperProofText: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: "800"
  },
  textScroll: {
    backgroundColor: "#000000",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1E2433",
    padding: 12,
    maxHeight: 220
  },
  terminalText: {
    color: "#A5B4FC",
    fontFamily: "monospace",
    fontSize: 10.5,
    lineHeight: 16
  },
  bundleActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12
  },
  actionPill: {
    flex: 1,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center"
  },
  actionPillText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700"
  },
  actionPillPrimary: {
    flex: 1.4,
    backgroundColor: colors.surface,
    borderColor: colors.danger,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center"
  },
  actionPillPrimaryText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "800"
  },
  submittedCard: {
    backgroundColor: "#0A2216",
    borderColor: colors.success,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16
  },
  submittedTitle: {
    color: colors.success,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 4
  },
  submittedBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18
  },
  loopButton: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center"
  },
  loopButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.5
  }
});
